### ISSUE TITLE
WebServer turns itself off.

### ISSUE THREAD

**Issue by dschuermann** [sufficientlysecure/ad-away#341]
_Original author: GiantWaf...@gmail.com (November 10, 2012 19:39:55)_

<b>What steps will reproduce the problem?</b>

1. Turning on the Tablet.  The problem occurs when first booting up,
so I don't know if it will show up in the log.

<b>2.</b>

<b>3.</b>

What is the expected output?  What do you see instead?

I expect the WebServer to be running, since I have both settings for it enabled
(Enable WebServer &amp; Enable WebServer at Boot).

<b>Please enable Debug Logging in preferences of AdAway, install aLogcat and</b>
<b>save a logfile while reproducing the problem. The logfile can be attached</b>
<b>to this issue.</b>

Log file is attached, but like I said, the problem occurs when first booting up, so I don't know if it will show up in the log.

What version of AdAway are you using? What Android version?
What custom rom?

ICS v4.0.4, Factory stock ROM, Rooted w/A1 OverClocking Kernel installed.

<b>Please provide any additional information below.</b>

It does not do it on my wife's identical tablet.

It did this right from go, after first setting up my tablet, before installing all my apps.

Samsung Galaxy 10.1&quot; P7510 32GB WiFi Tablet
ICS v4.0.4, Rooted, w/A1 OverClocking Kernel

Doesn't matter if it's OC'ed or not when this problem occurs.

Also, you should let people know in this screen that aLogCat
Will keep running forever and you have to tell it when to save.
I sat there waiting for it to finish for 20 minutes before
I figured it out.  That's why the log is so big.

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=340_

**Comment by 0-kaladin** [comment]
Closing as very old and would need to be retested on latest version.
