### ISSUE TITLE
Switch to cyanogenmod.org

### ISSUE THREAD

**Issue by dschuermann** [sufficientlysecure/ad-away#410]
_Original author: domschuermann@gmail.com (March 12, 2013 12:31:25)_

Sidenote: in the Strings.xml file (no_root_description key to be precise) you refer to cyanogenmod.com (in the English translation.
They recently switched to cyanogenmod.ORG, which I already fixed in my translation, but would be worth changing in other translations as well. 

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=409_

**Comment by 0-kaladin** [comment]
resolved in https://github.com/sufficientlysecure/ad-away/commit/b54cb49e06f36efb9fe22ffe51a093ab95f4865f
