### ISSUE TITLE
Some content is not shown, even if it is no ad

### ISSUE THREAD

**Issue by dschuermann** [sufficientlysecure/ad-away#430]
_Original author: RRichig...@gmail.com (April 05, 2013 12:41:41)_

<b>What steps will reproduce the problem?</b>
1. Download the App &quot;20 Minuten Online&quot; (or go to www.20min.ch)
2. Go in the app to the bottom and click on &quot;Sport - Resultate und Tabellen&quot; (or click on &quot;Sportresultate&quot;)
3. The content is now loading, but it is not shown, thus, the contant is interpreted as ad, even if it is real content - no idea why;).

<b>What is the expected output? What do you see instead?</b>
Usually, you should see the content

<b>Please enable Debug Logging in preferences of AdAway, install aLogcat and</b>
<b>save a logfile while reproducing the problem. The logfile can be attached</b>
<b>to this issue.</b>

<b>What version of AdAway are you using? What Android version? What custom</b>
<b>rom?</b>
2.2 (41) on Android 4.1.2 (i9300XXELL4)

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=429_

**Comment by 0-kaladin** [comment]
Old and seems like just needed to add a host to whitelist.
