### ISSUE TITLE
Refuses to recognize root after phone reset

### ISSUE THREAD

**Issue by psychorax** [sufficientlysecure/ad-away#522]
My HTC One X runs verison 4.0.7 of the ViperX custom ROM which comes with Superuser built in. Everythiing was fine, including AdAway, until I had to reset my phone this morning. Since then after restoring everything, AdAway is the only root app that refuses to recognize root. What's worse is that it just shows a dialog saying there's no root, and exits. There should be a way to test root access and request it so one can see whether it works.

**Comment by 0-kaladin** [comment]
Closing as this is very old would need to be re-tested on latest version.
