### ISSUE TITLE
stop redundant checking for newer hosts

### ISSUE THREAD

**Issue by hunleyd** [sufficientlysecure/ad-away#531]
If you turn on the 'check for updates' daily and it finds an update to the hosts file, you get a notification icon. Click that notification icon, it launches the app and immediately checks *again* for an update. You already know there's an update, don't bother checking. Clicking on the 'update available' notification should launch the app and right into the 'download and apply' process.

**Comment by 0-kaladin** [comment]
true but it is only checking again cause you have checked to check for updates on application launch.  removing that check box and you will just have to apply..
