### ISSUE TITLE
Ads in Youtube app v5.9.0.10

### ISSUE THREAD

**Issue by delro92** [sufficientlysecure/ad-away#533]
What steps will reproduce the problem?
1.Open the youtube app.
2.Start a few videos until you find one with an ad. Usually the third one since launching the app.
3.Then you have to watch the ad before the actual video starts.

What version of AdAway are you using? What Android version? What custom
rom?

AdAway version: 2.8.1
YouTube version: 5.9.0.10
Android version: 4.4.4
ROM: Paranoid Android 4.5 beta 2
Device: Nexus 4 (Mako)

**Comment by 0-kaladin** [comment]
The method AdAway uses to block ads doesn't work in for the Youtube app.  They don't rely on dns hostname resolution to play ads.
