### ISSUE TITLE
Nexus 5 (hammerhead) 4.4.4 roms overwrite hosts file on boot

### ISSUE THREAD

**Issue by pyr0ball** [sufficientlysecure/ad-away#534]
After updating to a 4.4.4 rom on my Nexus 5, I noticed adblock was no longer working. I was able to download and apply a patched host file, but upon reboot the patching was reverted to the default hosts file. After tinkering I found that there was a second hosts file in /system/etc/ called hosts.og. It appears there is now a script built into 4.4.4 that renames the current hosts file to hosts.alt and copies hosts.og in place of the existing hosts file on boot. In order for adaway's patch to remain on 4.4.4, it must also patch /system/etc/hosts.og

**Comment by 0-kaladin** [comment]
This is the only report I see if this.  reopen issue if you see this on any other device/rom.
