### ISSUE TITLE
Version 2.9.1 crashes

### ISSUE THREAD

**Issue by Gitoffthelawn** [sufficientlysecure/ad-away#538]
New version 2.9.1 crashes when clicking the Refresh button, the 'Host sources' menuitem, and the 'Your Lists' menuitem.  Error message for all three is: 'Unfortunately, AdAway has stopped.'  Never a problem with previous versions.

Have not tried uninstalling and reinstalling because have added items to blacklists/whitelists and do not want to lose them (and cannot see or export them due to the crashes).

Selecting 'Open hosts file' and 'Preferences' works as expected.

Tested on KitKat.

**Comment by nyuszika7h** [comment]
Next time you can use [oandbackup](https://f-droid.org/repository/browse/?fdid=dk.jens.backup) to back up AdAway's data.
