### ISSUE TITLE
URL parsing

### ISSUE THREAD

**Issue by Nick-White** [sufficientlysecure/ad-away#548]
If I want to add a whitelist or blacklist entry, the quickest way would
be to copy web address or image location, then paste in AdAway. But it
fails validation, so you have to strip the protocol and the path,
leaving only the domain.
Couldn't it be possible to parse the URL and automatically obtain the domain?

**Comment by 0-kaladin** [comment]
Possible, yes but will more than likely never be implemented as you can add from the dns log which won't have the protocol or path.
