### ISSUE TITLE
why my hosts source can't load?

### ISSUE THREAD

**Issue by bluelovers** [sufficientlysecure/ad-away#559]
my hosts source
https://gist.github.com/bluelovers/7745eab38eb641e85a73/raw/adaway.hosts.txt

i add my hosts file on source list

but it can't work
![screenshot_2014-10-29-17-49-26](https://cloud.githubusercontent.com/assets/167966/4823686/b8584b1c-5f51-11e4-9f47-4bcce6b3da2b.png)

**Comment by 0-kaladin** [comment]
I've loaded my own just fine, check the format.
