### ISSUE TITLE
2.9.2 issues for 2 day now

### ISSUE THREAD

**Issue by bacardilimon** [sufficientlysecure/ad-away#561]
Anytime I try and download anything from XDA or Dropbox I get blocked.only way for me to use it is to disable adaway. Tried 4 different browsers.

**Comment by 0-kaladin** [comment]
This would be something to whitelist so follow https://github.com/sufficientlysecure/ad-away/wiki/Solutions
I believe this was discussed in the forums if you use tapatalk.
