### ISSUE TITLE
note 4 n910u clash with S health

### ISSUE THREAD

**Issue by ross350** [sufficientlysecure/ad-away#565]
Hi
so when I install adaway on my note 4 and try to open s-health it just freezes. It stops once I reinstall it so I really hope you can fix this with an update.
this is my first android device so I'm not sure how to give you actual log data about the error. But please let me know if I can help. Or if there is some simple fix that I'm just oblivious to.
thanks

**Comment by 0-kaladin** [comment]
I've used S-health just fine with adaway on the s6 but this isn't something we would fix in the source but rather you would fix by identifying the whitelist entry.  Please follow: https://github.com/sufficientlysecure/ad-away/wiki/Solutions
