### ISSUE TITLE
Adaway interferes with GPS function

### ISSUE THREAD

**Issue by bankanidhi** [sufficientlysecure/ad-away#576]
I have tested on two different devices. ATT LG G3 and Galaxt Note 3 T-Mobile.

As soon as i install Adaway and enable the host file and reboot the system GPS stops working. I can see satellite but no fix at all over 10-15 min. Without adaway it would fix in less than 30 sec.

**Comment by 0-kaladin** [comment]
I use GPS all the time with adaway on multiple devices and in the forums where there are thousands of users no one else has reported this.  I can't imagine editing the hosts file on android would break GPS.  You can Log DNS requests to see if anything is coming in but seems like weird one off case.
