### ISSUE TITLE
Causes Star Wars Commander to crash

### ISSUE THREAD

**Issue by unknownsoldierx** [sufficientlysecure/ad-away#577]
If I have adaway enabled Star Wars Commander crashes during the loading screen. I disable adaway, reboot, and the game works fine.

**Comment by nyuszika7h** [comment]
Have you tried enabling the web server?

**Comment by xortim** [comment]
Yup. It still crashes. The only way I've gotten it to work is to log the DNS requests and whitelist everything that it tries to reach

**Comment by TameOfGroans** [comment]
Have you instead tried MinMinGuard?

**Comment by Opticz** [comment]
I went through the entire list of DNS requests and finally only had to whitelist 
`connect.tapjoy.com`
for SWC to get past the loading screen.
