### ISSUE TITLE
on android 5.0.1 adaways internal webserver does not autostart

### ISSUE THREAD

**Issue by lemmy04** [sufficientlysecure/ad-away#580]
I'm running adaway on a (rooted, of course) nexus 10 running android 5.0.1, adaway has root permissions, and works fine, except that the internal webserver isnt autostarting.

**Comment by ericcotelnu** [comment]
Thank you 😀

**Comment by lemmy04** [comment]
...will that changed version appear in f-droid repository?

**Comment by nyuszika7h** [comment]
@lemmy04 You should open an issue on https://gitlab.com/fdroid/fdroiddata for that. In general, they only tend to push actual releases there, but they do sometimes push git versions.
