### ISSUE TITLE
When a Host Source is unavailable, AdAway never times out

### ISSUE THREAD

**Issue by Gitoffthelawn** [sufficientlysecure/ad-away#583]
Sometimes a Host Source is unavailable.  In particular, host-file.net/ad_servers.asp is sometimes unavailable.

When a Host Source is unavailable, AdAway never times out, and just spins forever.  Android has to be restarted to get it out of this state.

When a Host Source is missing, may I recommend allowing the user to select 1 of 3 options:
1. Abort the update
2. Continue with the update, but use the existing local Hosts file as an additional temporary Host Source (this way, it minimizes the effect of a temporarily missing Host Source).
3. Continue with the update, but only use available Host Sources (this will result in some hosts likely not being blocked, and thus is not ideal).

**Comment by ericcotelnu** [comment]
All 3 being available would be optimal :)

**Comment by Gitoffthelawn** [comment]
I agree.

**Comment by 0-kaladin** [comment]
Adaway times out, #651 is the most recent request.
