### ISSUE TITLE
Web server won't stay running. 

### ISSUE THREAD

**Issue by eecummings** [sufficientlysecure/ad-away#585]
Setting won't stick. 
Nexus 9, Android 5.0.0, rooted.

**Comment by ericcotelnu** [comment]
Logcat says for me, the binary needs to be a PIE format ELF binary, that's why.

**Comment by ericcotelnu** [comment]
Running 5.0.2 here, on my S4 Mini. I tried running the .so from a terminal, then it spat out the message able needing to be what I posted before.

**Comment by 0-kaladin** [comment]
if you use this unofficial build it resolves that PIE issue.
https://www.androidfilehost.com/?fid=95916177934531241
