### ISSUE TITLE
whitelist not working well

### ISSUE THREAD

**Issue by automatorMaxima** [sufficientlysecure/ad-away#587]
the syntax it accepts is rather quirky. usually, it'd work if I used, for example,

www.inc.com/*

which means all pages under this domain should be excluded from adblock, but it didn't allow me to add that. So I added,

inc.com
www.inc.com
www.inc.com*

but it still didn't work. I can at most access the homepage and see the top header, but the menu and main body content is blank.

Please advise!

**Comment by TameOfGroans** [comment]
Adaway only filters hosts

From that list comprising three lines above only the first two are hosts.

While the third entry is technically valid I am not aware of any TLD other than Com which would match.


for other questions of use:

https://github.com/dschuermann/ad-away/wiki/
