### ISSUE TITLE
SaferTaxi

### ISSUE THREAD

**Issue by ghost** [sufficientlysecure/ad-away#591]
AdAway seems to block the display of the taxi driver's information and stopped the ap from working.  When I disabled AdAway and restarted, AdAway worked fine.  
That aside, AdAway works very well.  Thanks!

Alex

**Comment by 0-kaladin** [comment]
Please follow this https://github.com/sufficientlysecure/ad-away/wiki/Solutions to whitelist what is needed for the app to function as you expect.
