### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by Techman-** [sufficientlysecure/ad-away#592]
This isn't exactly a required feature or even a real issue, but a visual overhaul to material design would be nice. It's one of those only apps left that I use that have an older UI. 

Android has design docs on their website for all developers to refer to, as always.

**Comment by nyuszika7h** [comment]
You should be able to do this using AppCompat, although that will force Material Design on users of older Android versions too.

**Comment by 0-kaladin** [comment]
@dschuermann this can be closed

**Comment by dschuermann** [comment]
@0-kaladin I gave you now write access to this repo, you can also close issues etc :)
