### ISSUE TITLE
AdAway force closes

### ISSUE THREAD

**Issue by pkramerruiz** [sufficientlysecure/ad-away#594]
They're my sources:
http://www.hosts-file.net/download/hosts.txt
http://cznic.dl.sourceforge.net/project/adzhosts/HOSTS.txt
http://www.malwaredomainlist.com/hostslist/hosts.txt
http://sysctl.org/cameleon/hosts
http://someonewhocares.org/hosts/hosts
http://hostsfile.mine.nu/Hosts
http://hosts-file.net/ad_servers.txt
http://www.hostsfile.org/Downloads/hosts.txt
http://adblock.mahakala.is
https://adaway.org/hosts.txt
http://winhelp2002.mvps.org/hosts.txt
http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext

AdAway 2.9.2 from F-Droid. 
Device: OnePlus One, Android 4.4.4 cm11-201510105-Nightly

AdAway downloads files, analyzes and when applying whitelist /blacklist it crashes.
The only thing I wrote into whitelist is:
*facebook*
*gameloft*

**Comment by pkramerruiz** [comment]
**facebook**
**gameloft**

**Comment by pkramerruiz** [comment]
With wildcat before and after both

**Comment by SelfDestruct68** [comment]
Remove Adblock.mahakala.is 
it isn't a txt file thus not usable by adaway
