### ISSUE TITLE
False detection on ad-away

### ISSUE THREAD

**Issue by yccheok** [sufficientlysecure/ad-away#596]
I have a stock market app, which will perform the following request, to get stock suggestion from Yahoo server

    http://d.yimg.com/aq/autoc?query=PG&region=US&lang=en-US&callback=YAHOO.util.ScriptNodeDataSource.callbacks

However, ad-away false thought that's Advertisement request.

I had asked my client to put the following URL as white list

    http://d.yimg.com/
    http://d.yimg.com/aq/autoc

However, that's doesn't work. May I know what is the workaround for that?

Thanks.

**Comment by TameOfGroans** [comment]
AdAway does NOT filter on URL but on hosts. 

The host is the part between the protocol and the path

protocol
http

protocol prefix
http://

host
allads.areevil.tld 

path
/injure.users/for.money.php&culpability=true

**Comment by TameOfGroans** [comment]
LogDNSrequests will help you yourself identify what is being blocked. View log, long click hosts to WhiteList

**Comment by TameOfGroans** [comment]
check for updates and mash apply button to integrate changes.

**Comment by nyuszika7h** [comment]
Try whitelisting `d.yimg.com` rather than `http://d.yimg.com/`.
