### ISSUE TITLE
[Nexus 5] Audio glitching/suttering when hosts file is applied

### ISSUE THREAD

**Issue by danarnold** [sufficientlysecure/ad-away#604]
When AdAway is applied to the hosts file and music is playing over the headphone jack, every time there is one or more network requests made (and particularly when there are a lot of network requests made), the audio will glitch and stutter; it will stop playing and buzz for a split second, often repeatedly and of varying lengths.

It took a lot to determine that it was actually AdAway causing this, as I had no reason to suspect it over any other app. I diagnosed with a clean flash and reinstalling any root apps one-by-one.

Steps to reproduce:
1. Install Android 5.0.1
2. Root
3. Install Spotify / Google Play Music / etc.
4. Install AdAway, apply hosts
5. Play a song
6. Make network requests (e.g. load web pages in Chrome, load image galleries in sync for reddit)

This issue also goes away when the hosts file is returned to normal.

**Comment by TameOfGroans** [comment]
Replace AdAway with UnbelovedHosts. Re-test. Results?

**Comment by TameOfGroans** [comment]
Optionally first exclude yourself from bug 580 

https://github.com/dschuermann/ad-away/issues/580

**Comment by danarnold** [comment]
Using the build linked in #580 fixes it.
