### ISSUE TITLE
Malware Domains hosts source is ignoring

### ISSUE THREAD

**Issue by mikhaelkh** [sufficientlysecure/ad-away#606]
1) Disable all items in *Hosts sources*
2) Add http://mirror1.malwaredomains.com/files/justdomains to the list of *Hosts sources* and enable it
3) Click *Download files and apply ad blocking* in the main window
4) Click *Open hosts file*
You can see that AdAway ignored all hostnames in the source mentioned above, probably because this source is just hostnames list, without IPs to redirect. Please, redirect all hostnames from this source to 127.0.0.1 (or 0.0.0.0) instead of skipping them.

**Comment by mikhaelkh** [comment]
Please somebody fix this! The list contains over 16,000 domains!

**Comment by 0-kaladin** [comment]
you can use http://www.malwaredomainlist.com/hostslist/hosts.txt and it'll work just fine.

**Comment by mikhaelkh** [comment]
@0-kaladin, malwaredomainlist.com and malwaredomains.com provides 2 different hosts lists, but malwaredomains.com doesn't add 127.0.0.1 or 0.0.0.0 or any IP before the hosts. Thus, ad-away ignores this list

**Comment by 0-kaladin** [comment]
they do and the one i provided is much more inclusive.  There are tons of malware domain lists that provide their lists in hosts file format.  There is no reason to have adaway support random other formats for hosts mean for DNS BL.  Just find a list in hosts format like what I provided.  Go ahead and compare the lists.

**Comment by mikhaelkh** [comment]
> they do and the one i provided is much more inclusive.
http://mirror1.malwaredomains.com/files/justdomains - 9345 domains.
http://www.malwaredomainlist.com/hostslist/hosts.txt - 1431 domains.
