### ISSUE TITLE
Block App's

### ISSUE THREAD

**Issue by ggkameleon** [sufficientlysecure/ad-away#608]
Hi I have Adaway and I have 3 App's don't works : Gulli Tv - Zouzou 
I apply the request DNS and logs journal and create white list but don't works again and more can download App in Aptoid for version work in my Android Kitkat box Tv because the Playstore don't give me the good App's. 
I don't understand to make an white list ? 
In my jailbreak iOS I have Adblock and I can choose App for apply.. I must stop Adaway

**Comment by 0-kaladin** [comment]
Please follow this for details: https://github.com/sufficientlysecure/ad-away/wiki/Solutions
