### ISSUE TITLE
Android 5.1 cannot write to system, symlink not working

### ISSUE THREAD

**Issue by morgenstern72** [sufficientlysecure/ad-away#610]
Nexus 10, Android 5.1
No location of host file works
I can Copy the host file from data/data to system/etc with es Explorer, works. But adaway cannot update the list there and it will not be used from ans other locatiob

**Comment by Poeschl** [comment]
I have the same problem. It seems that in Android 5.1 the default host file is missing. After creating a empty one on the system partition and creating a link via a zip file I found on the internet. I was able to bring it back to work with the data/data/hosts location. 

I will take a closer look today and may bring up a pull request to fix it.

**Comment by Poeschl** [comment]
Looked at the code and don't found anything bad. Tested with a compiled app from the master branch and it seem to work again.

**Comment by Poeschl** [comment]
Until I restarted the app. -.-

**Comment by Poeschl** [comment]
Update from my side: After the update to 5.1.1. It works for me again with the symlink to /data/data/hosts over the provided zip file.
