### ISSUE TITLE
"Download failed" error every morning

### ISSUE THREAD

**Issue by endolith** [sufficientlysecure/ad-away#612]
Every morning my phone says "Download failed" for Ad-Away, then I go into Ad-Away and press the button and it works fine.  Is there a way to hide this error?  Maybe it is checking at a specific time each day, which just happens to be the time I leave Wi-Fi to go to work, and it could try again a few times before giving this error?  Maybe the time could be adjusted?

![screenshot_2015-04-15-09-39-42](https://cloud.githubusercontent.com/assets/58611/7160410/e2712aca-e356-11e4-9dca-8a9493097662.png)

**Comment by endolith** [comment]
It looks like it checks at 9 am every morning?

**Comment by 0-kaladin** [comment]
try this build https://androidfilehost.com/?fid=24052804347787499
it will use a different random time for update, not 9am.

**Comment by breversa** [comment]
I gave this build a try, but the problem keeps happening, usually when I wake up in the morning and disable airplane mode on my phone.

I also saw that error when coming home in the evening, when my phone connects to my wifi network (I have the "only update on wifi" option on).
