### ISSUE TITLE
Snapchat issues

### ISSUE THREAD

**Issue by Heisendres** [sufficientlysecure/ad-away#616]
I think AdAway blocks some snapchat's login server and I can't log in when AdAway is applied, neither server is detected by the DNS register (Sorry if my English is bad). Hope you fix this asap

**Comment by 0-kaladin** [comment]
There is nothing we can fix.  Please read this: https://github.com/sufficientlysecure/ad-away/wiki/Solutions
Adaway only applies hosts file to android.  It automates this process and provides a default set of lists.  If one of those hosts are blocking something you use you need to find that url described in the solutions above and whitelist it.  This will solve your problem.
