### ISSUE TITLE
onclickads.net

### ISSUE THREAD

**Issue by ascrounch** [sufficientlysecure/ad-away#619]
Fu*king ads on this adress : 

Onclickads.net

**Comment by 0-kaladin** [comment]
https://github.com/sufficientlysecure/ad-away/wiki/BlockNewAds
add it to your blacklist but it has been in one of the default sources for a while now: http://hosts-file.net/default.asp?s=onclickads

**Comment by Sherry25** [comment]
There is a post that mainly discusses Onclickads.net. If wanting to know more its information and the useful  methods to remove it, you can read the post and follow the recommended methods.

http://pc-superman.com/remove-ads-by-onclickads-net-from-web-browser-step-by-step/
