### ISSUE TITLE
Jackbox.tv

### ISSUE THREAD

**Issue by spdyrel** [sufficientlysecure/ad-away#622]
Please add Jackbox.tv to the whitelist. With Adaway enabled it just shows a white page. It is used as a controller to play games from the Jackbox Party Pack. I tried adding it to my own whitelist but it's still being blocked (works when disabling ad blocking). Thanks!

**Comment by 0-kaladin** [comment]
You can manually add jackbox.tv to your whitelist.  If it is still being blocked then that means there are other domains that you will need to whitelist besides that one.  You can follow this guide and Log DNS requests to figure out which other domains need to be whitelisted: https://github.com/sufficientlysecure/ad-away/wiki/Solutions

**Comment by IraJacobs** [comment]
Using the DNS request logger, I added this to my whitelist and it seems to be working now, albeit with an ad:
safebrowsing.googleapis.com

**Comment by tannerkrewson** [comment]
@IraJacobs's solution didn't work for me. I added the following to the whitelist, and it works now:

www.google-analytics.com
