### ISSUE TITLE
Adds on ajaxshowtime.com (mobile version)

### ISSUE THREAD

**Issue by chimanba** [sufficientlysecure/ad-away#627]
Tried the method to blacklist myself but without success.

When surfing on ajaxshowtime.com on my smartphone, I always see adds from Philips (see screenshot).

![screenshot_2015-05-16-10-14-52](https://cloud.githubusercontent.com/assets/12471316/7665601/fd1677dc-fbbf-11e4-86e1-a996fad4ff42.png)

Can someone help me to block those adds?

Thanks in advance.

**Comment by 0-kaladin** [comment]
they could be built in and not blockable by a hosts list file.  You can ensure you tried what is described here: https://github.com/sufficientlysecure/ad-away/wiki/Solutions
