### ISSUE TITLE
Failed ignoring a site that detects AdAway

### ISSUE THREAD

**Issue by Shohreh** [sufficientlysecure/ad-away#629]
Hello,

I use AdAway on Cyanogenmod to block ads.

One site I read often has added some code to detect ad blockers, and refuses access until it's disabled.

So I whitelisted this site through (menu) > Your Lists > White, added www.acme.com, and rebooted, but it stills detects an ad blocker.

Why is that? How to tell AdAway to ignore this site?

Thank you.

**Comment by 0-kaladin** [comment]
There must be more domains on the site that you need to whitelist.  Keep adding to the white list and remember you need to reboot after making adjustments.  Can follow this for details https://github.com/sufficientlysecure/ad-away/wiki/Solutions
but there is nothing adaway can do here you just need to find the url(s) to allow.
