### ISSUE TITLE
Toggle on/off

### ISSUE THREAD

**Issue by daniel-lo** [sufficientlysecure/ad-away#632]
Quite often the filter stops web pages from loading. Instead of extensively maintaining the white list .. especially when it's only for one time .. it would be good to have some kind of a quick toggle .. floating, status bar, widget (don't know).

**Comment by 0-kaladin** [comment]
This is really what the white list is for.  Also a quick toggle won't work as you have to re-apply adaway and reboot for the changes to take effect.  Your best option is the white list or stop using such sites.

**Comment by daniel-lo** [comment]
Well .. many Sites that aren't malicious are connected to Ad-networks or
some kind of tracker. What usually happens is that I see the unreachable
url .. which I then have to memorize .. to manually add it to the whitelist
.. that isn't very convenient. I thought there might be some kind of
workaround for this.

2015-08-24 23:57 GMT+02:00 0-kaladin <notifications@github.com>:
