### ISSUE TITLE
Pulls data exactly on the full hour

### ISSUE THREAD

**Issue by hgmichna** [sufficientlysecure/ad-away#635]
It may be unwise to try to pull data exactly on the full hour, because that is a point in time that is often chosen, for example for activities on servers (also unwisely, but we cannot help it).

In my case Adaway pulls data always exactly at 9:00 am, which is not a very good time anyway, because it is a time when people are likely to use the phone. For me, to give one example, some time in the middle of the night would be preferable. But please do not make it configurable. There is already far too much to configure on all smartphones. It should be automatic.

It would be much worse if many Adaway instances worldwide attempted to pull data at the exact same time, like exactly on the full hour. Perhaps this is so and this is the reason why Adaway takes such a long time to pull data, needlessly wasting RAM occupation, data, and battery.

There are various ways to make sure that data pulls are evenly distributed over time, but some simple random distribution over a few hours would already be a significant improvement.

**Comment by dschuermann** [comment]
Unfortunately, AdAway is currently not actively developed by me, but yes this TODO is very high on my personal priority list, because at exactly 9:00 my server is overloaded ;)
I am open for pull requests to solve this!

**Comment by 0-kaladin** [comment]
Would love to see how many hits you get on avg today at 9am vs a month from now to see really the impact this may have had.
