### ISSUE TITLE
It is not asking for root permission and not blocking ads

### ISSUE THREAD

**Issue by cyberman07** [sufficientlysecure/ad-away#638]
Its gets installed it asks for reboot but never asks for root access and is blocking ads in old apps. if i install a new app its not blocking it

**Comment by Primokorn** [comment]
Which version of AdAway do you have? Which Android version? SuperUser or SuperSU?

**Comment by cyberman07** [comment]
Adway 3.0(52).
Android 4.4.4
SuperSU PseudoPro v2.46

Right now its showing in SuperSU but ads in "Learn Piano" app is not
getting blocked rest of the apps are fine

On Thu, Aug 6, 2015 at 7:59 PM, Primokorn <notifications@github.com> wrote:

> Which version of AdAway do you have? Which Android version? SuperUser or
> SuperSU?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sufficientlysecure/ad-away/issues/638#issuecomment-128392095>
> .
>



-- 
Yesterday is History
Tomorrow is a mystery,
But Today is aGift, that is why its called PRESENT.........

**Comment by Primokorn** [comment]
In AdAway, select 'Log DNS Requests' > 'TCPDUMP is not running!'
Return to your homescreen then open 'Lear Piano' app and browser a few pages until an ad is displayed.
Return to AdAway > Selection 'Log DNS Requests' > 'TCPDUMP is running!' top stop logging
Click on 'Open log file'. See if some of the listed domains could generate the ads. If so, press and hold down the domains to add them to your blacklist.
Update AdAway from the main screen then try again.

**Comment by cyberman07** [comment]
Its Not working i did it . Please find the attachments.

**Comment by 0-kaladin** [comment]
If there is one app not being blocked, either you need to follow this https://github.com/sufficientlysecure/ad-away/wiki/Solutions to find what hostname to blacklist or the app is able to bypass this which is also described in the wiki.
