### ISSUE TITLE
Use new location of http://hosts-file.net

### ISSUE THREAD

**Issue by dschuermann** [sufficientlysecure/ad-away#643]
new location is at http://hosts-file.net/download/hosts.txt

**Comment by engstk** [comment]
http://hosts-file.net/ad_servers.txt is still active and updating on the 5th August

**Comment by dschuermann** [comment]
Yes but it's now longer the preferred URL according to their site.

**Comment by engstk** [comment]
Where did you read that?

That link always existed and it has always older hosts than ad_servers.txt

Different purposes.

**Comment by dschuermann** [comment]
I looked at the downloads and the old link was no longer there, but you are right we should switch to "http://hosts-file.net/ad_servers.txt" and not "http://hosts-file.net/download/hosts.txt". Currently it's "http://hosts-file.net/ad_servers.asp".

**Comment by PertR** [comment]
What is the new address?
