### ISSUE TITLE
NFL Mobile android application not allowing videos to be played

### ISSUE THREAD

**Issue by mottchew** [sufficientlysecure/ad-away#648]
NFL Mobile android application not allowing videos to be played when ad-away is enabled.

I have tried adding many different things to the whitelist. but no joy. Any ideas

**Comment by 0-kaladin** [comment]
Please follow the suggestions here: https://github.com/sufficientlysecure/ad-away/wiki/Solutions
and try Logging DNS Requests to allow what is needed for the videos.
