### ISSUE TITLE
Kim Kardashian: Hollywood game/app force closes @ loading screen- Unable to play at all

### ISSUE THREAD

**Issue by GA11** [sufficientlysecure/ad-away#652]
This hasn't happened until recently, any solutions are greatly appreciated as I cannot play the game. Thank you!

**Comment by 0-kaladin** [comment]
Please follow the suggestions here: https://github.com/sufficientlysecure/ad-away/wiki/Solutions
and try Logging DNS Requests to allow the url the game needs to run.

**Comment by GA11** [comment]
I have followed all those steps & added specific url's to my Whitelist from the DNS Requests, but nothing has changed. I've rebooted multiple times. I even uninstalled Adaway, then reinstalled. I would still appreciate any other help, if I need to send screenshots or anything just let me know. There is literally no other tips I can find through google/youtube etc. Thank you for your fast reply, & for all the help again.

**Comment by 0-kaladin** [comment]
did you reboot after adding to the whitelist?

**Comment by GA11** [comment]
Yes, a bunch of times :-/ I'm so upset, I really thought "whitelisting" what the DNS Log showed would get it to open- still no progress. I cannot uninstall the Kim Game as it does not backup your progress, & I have been playing for almost a year.

**Comment by GA11** [comment]
If this helps at all, I decided to click "scan for adware" within the adway app, & this is what it says. I am very confused though as I have another game installed by the same developer, that also shows up as "adware", but still opens/works properly & is playable. 
![2015-08-24 23 28 00](https://cloud.githubusercontent.com/assets/13934884/9458121/c1e64be0-4ab8-11e5-91da-13dab5a805ca.png)

**Comment by 0-kaladin** [comment]
if you disable the hosts list and reboot does the app work?  if not i'd say the app developer is actively ensuring you can't use an adblocker.

**Comment by GA11** [comment]
No, when I disable the the hosts & reboot, sadly the app still does not open :-( I believe what you said is the case. That's why I'm stuck & unsure what to do next. Do you have any ideas what my next step should be? I'd like to try everything possible before uninstalling the game, thank you again!

**Comment by 0-kaladin** [comment]
There is nothing left to try.  The app developer has made this decision so either he is losing users who chose to block ads or you need to chose to uninstall adaway.

**Comment by GA11** [comment]
Thank you for your help. Once I uninstall adaway, are there any files left on my phone that need to be removed? Unfortunately uninstalling adaway did not help. Thanks again.
