### ISSUE TITLE
Not working in toonmania

### ISSUE THREAD

**Issue by kriki200** [sufficientlysecure/ad-away#653]
Hi, I've tried switching the location of the host file as suggested in the description and also cleaning cache but the adds are still appearing. I've added a screenshot so uou can see the problem, I'm currently on 4.4.4.
![screenshot_2015-08-24-15-23-33](https://cloud.githubusercontent.com/assets/13945483/9441244/25c40056-4a75-11e5-86c7-183ab7771d82.png)

**Comment by 0-kaladin** [comment]
Please follow the suggestions here: https://github.com/sufficientlysecure/ad-away/wiki/Solutions
and try Logging DNS Requests to block the ads.  Also try running AdAway webserver.

**Comment by kriki200** [comment]
I've tried everything thats in the help menu and it still shows them, I've
even deleted the cache of the app everytime I blocked new IP's but it still
shows them (I did reboot the phone everytime after adding them to blocked
list)...
24. avg. 2015 23:52 je oseba "0-kaladin" <notifications@github.com>
napisala:
