### ISSUE TITLE
Android: Unable to white list some domains with error "Improperly formatted hostname"

### ISSUE THREAD

**Issue by sylverpyro** [sufficientlysecure/ad-away#655]
I'm trying to white list some domains that are getting blocked with the default ad-away lists (such as jackbox.tv) via '...' -> Your Lists -> Whitelist -> '+'.  However when I go to add the domain 'jackbox.tv' I get an "Improperly formatted hostname: This is not a valid hostname!" error.  I'm able to add other hostnames just fine (such as 'fitbit.com' and '*.fitbit.com').  

I know the hostname I'm trying to enter is valid as nslookup and dig both return DNS results for the name.

**Comment by 0-kaladin** [comment]
related to #622

**Comment by 0-kaladin** [comment]
I just looked at the regex and looks fine.  i tested on my AdAway and can successfully add 'jackbox.tv' to my whitelist.  Are you sure you don't have any spaces or something in it?

**Comment by sylverpyro** [comment]
Aw shoot. I see where the issue was coming in. It is a whitespace that's
throwing it off, but it's a whitespace at the _end_ of the URL inserted by
by Android's keyboard settings. So it was getting entered as 'jackbox.tv '
instead of 'jackbox.tv' . Maybe adding a feature to drop trailing white
spaces for the user could be helpful in these cases?

**Comment by 0-kaladin** [comment]
hmm i can make it better.  in fact the blacklist entry does your keyboard add a trailing whitespace as easily as in the whitelist entry?

**Comment by 0-kaladin** [comment]
This should fix it: https://github.com/sufficientlysecure/ad-away/commit/6d0cc48f4ef4f28eecfa5665153f0a5b5b346961
